[project]
name = "coding-basics"
version = "0.1.0"
description = "This project consists of hands on all the python programming basic concepts with proper docs."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    'pandas',
    'numpy',
    'notebook',
]
